# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 08:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20181116_0324'),
        ('ims', '0002_ltiapp_ltitenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitenant',
            name='badgr_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.BadgrApp'),
        ),
    ]
