# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_ltitenant_badgr_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitenant',
            name='lms_domain',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
